#!/bin/bash
#
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.

$GIT_DIR/hooks/commit-msg.unchanged.sh || exit $?
$GIT_DIR/hooks/commit-msg.editor.sh || exit $?
